language: python
dist: trusty
sudo: required
matrix:
    include:
        - python: 3.6
          env: PYENV=py36
install:
  - source tests/install.sh
script:
  - pytest --disable-pytest-warnings --cov=hbp_validation_framework tests/ --environment="production"
